### Import numpy library  

In [1]:
import numpy as np

### Create an Array using array function  

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

### Create an Array containing numbers from 20 to 40 

In [3]:
arr2 = np.arange(20,41)
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

### Create an array which contain 10 elements and every element is 5  

In [6]:
fives = np.ones(10)*5
fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### create a 1-d array and then convert it into 3-d array  

In [8]:
arr3 = np.random.randint(1,50,24).reshape(3,4,2)
arr3

array([[[38,  8],
        [ 2, 42],
        [37,  4],
        [36,  7]],

       [[40,  7],
        [49,  2],
        [24, 28],
        [31, 22]],

       [[19, 40],
        [ 9, 49],
        [12, 28],
        [18,  9]]])

### Create 2-d array which contains random 25 numbers between 0 and 1 

In [9]:
arr4 = np.random.rand(4,5)
arr4

array([[0.12266483, 0.46474282, 0.2246158 , 0.420812  , 0.6132071 ],
       [0.32518442, 0.24517215, 0.75524836, 0.16724538, 0.25004266],
       [0.34648976, 0.81431851, 0.80775962, 0.51725626, 0.0695174 ],
       [0.94134018, 0.06089988, 0.72121184, 0.17114777, 0.80329767]])

### create array containing 20 random integer then replace every even number with -1 
#### Example - 
####                  array --- >  [44,55,12,6,3] 
####                  ouput ----> [-1,55, -1,-1,3]


In [29]:
np.random.seed(123)
arr5 = np.random.randint(1,50,20)
arr5[arr5 %2 == 0] = -1
arr5

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])

#### You have a matrix 
[[5 , 10, 15, 20, 25],
[30, 35, 40, 45, 50],
[55, 60, 65, 70, 75],
[80, 85, 90, 95, 100]]

Extract
[30,35,40]
[55, 60, 65]

In [34]:
matrix = np.array([[5 , 10, 15, 20, 25],
                   [30, 35, 40, 45, 50],
                   [55, 60, 65, 70, 75],
                   [80, 85, 90, 95, 100]])
matrix[1:3,0:3 ]

array([[30, 35, 40],
       [55, 60, 65]])

### Concatenate two 1-d array   

In [35]:
arr7 = np.array([1,2,3])
arr8 = np.array([4,5,6])
np.hstack((arr7,arr8))

array([1, 2, 3, 4, 5, 6])

### Stack 2-d matrix horizontally and vertically

In [36]:
matrix2 = np.random.randint(1,10,9).reshape(3,3)
matrix3 = np.random.randint(10,20,9).reshape(3,3)

In [37]:
matrix2

array([[5, 1, 1],
       [5, 2, 8],
       [4, 3, 5]])

In [38]:
matrix3

array([[17, 12, 14],
       [18, 10, 17],
       [19, 13, 14]])

In [40]:
np.vstack((matrix2, matrix3))

array([[ 5,  1,  1],
       [ 5,  2,  8],
       [ 4,  3,  5],
       [17, 12, 14],
       [18, 10, 17],
       [19, 13, 14]])